version: '3.8'
services:
  bot:
    build: .
    container_name: discord-github-bot
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped 