version: '3.8'
services:
  bot:
    build: .
    container_name: discord-github-bot
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src/db:/app/src/db
    restart: unless-stopped 